#!/usr/bin/env node
var program = require('commander');
program
    .option('-d, --date', 'display current date')
    .parse(process.argv);
var dt = new Date();
if(program.date) {
    console.log(dt.getFullYear()
    + '--'
    + (dt.getMonth() + 1)
    + '--'
    + dt.getDate()
    );
}